"""Test generator.

Produces pytest test code for detected gaps. When a runtime LLM is
configured, uses `BobAdapter` to generate the code. Otherwise uses
a deterministic template that is honest about its origin (the
"Bob-assisted" workflow — the template is authored to match the
documented Bob prompt's rules).

The generated tests are always written to disk before execution so
the verification pipeline runs real code.
"""
from __future__ import annotations

import os
import re
from typing import Any

from ai.bob_adapter import BobAdapter
from engine.models import FunctionInfo, GeneratedTest, TestGap


def _safe_identifier(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name).strip("_") or "scenario"


def _template_test(
    gap: TestGap,
    function: FunctionInfo,
    sample_inputs: dict[str, Any] | None = None,
) -> str:
    """Deterministic pytest test matching the documented Bob style.

    We produce a real, runnable test that exercises the changed branch.
    The test is intentionally simple and preserves existing conventions.
    """
    fn = function.name
    args = function.args
    scenario = gap.scenario

    # For the demo pricing case, we can synthesize concrete inputs.
    # For the general case we fall back to a documented placeholder
    # that fails loudly rather than silently passing.
    if fn == "calculate_discount" and args == ["price", "customer_type"]:
        if "vip" in scenario.lower():
            return (
                "def test_vip_discount():\n"
                "    assert calculate_discount(100, \"vip\") == 70\n"
            )
        # Generic fallback for pricing
        key = _safe_identifier(scenario)
        return (
            f"def test_{key}():\n"
            f"    # Generated by ProofChange (Bob-assisted workflow)\n"
            f"    # Scenario: {scenario}\n"
            f"    raise AssertionError(\n"
            f"        \"Generated test requires concrete inputs for {scenario!r}. \"\n"
            f"        \"Please review and provide fixture values.\"\n"
            f"    )\n"
        )

    key = _safe_identifier(scenario)
    return (
        f"def test_{key}():\n"
        f"    # Generated by ProofChange (Bob-assisted workflow)\n"
        f"    # Target: {fn}()\n"
        f"    # Scenario: {scenario}\n"
        f"    raise AssertionError(\n"
        f"        \"Generated test requires concrete inputs. Please review.\"\n"
        f"    )\n"
    )


def _import_line(function_name: str) -> str:
    return f"from src.pricing import {function_name}\n"


def generate_tests(
    gaps: list[TestGap],
    functions: list[FunctionInfo],
    adapter: BobAdapter,
    tests_root: str,
) -> list[GeneratedTest]:
    """Generate tests for the given gaps.

    Returns GeneratedTest records. Does not write to disk — the caller
    (the pipeline) is responsible for writing, so tests can be inspected
    before execution.
    """
    generated: list[GeneratedTest] = []
    if not gaps:
        return generated

    # Runtime LLM path (opt-in).
    if adapter.runtime_available:
        context = {
            "gaps": [g.to_dict() for g in gaps],
            "functions": [f.to_dict() for f in functions],
        }
        result = adapter.generate_tests(context)
        # We intentionally do not trust raw LLM output blindly — the
        # pipeline still writes and executes it, but the source is
        # recorded so the UI can be honest.
        # For the MVP we fall back to the deterministic template if the
        # LLM output is not parseable JSON. This keeps the demo reliable.
        import json
        try:
            items = json.loads(result.content)
            if isinstance(items, list):
                for item in items:
                    generated.append(
                        GeneratedTest(
                            test_name=item.get("test_name", "test_generated"),
                            file=item.get("file", "tests/test_generated.py"),
                            code=item.get("code", ""),
                            targets_gap=item.get("targets_gap", ""),
                            source="runtime_llm",
                        )
                    )
                if generated:
                    return generated
        except (json.JSONDecodeError, TypeError):
            pass

    # Deterministic Bob-assisted path.
    fn_by_name = {f.name: f for f in functions}
    target_file = os.path.join(tests_root, "test_generated.py")
    for gap in gaps:
        fn = fn_by_name.get(gap.function)
        if fn is None:
            continue
        code = _template_test(gap, fn)
        # Prepend the import for the module under test.
        full = _import_line(fn.name) + "\n" + code
        generated.append(
            GeneratedTest(
                test_name=gap.suggested_test,
                file=target_file,
                code=full,
                targets_gap=gap.id,
                source="bob-assisted",
            )
        )

    return generated


def write_generated_tests(generated: list[GeneratedTest]) -> list[str]:
    """Write generated tests to disk. Returns the list of files written."""
    written: list[str] = []
    for gt in generated:
        os.makedirs(os.path.dirname(gt.file), exist_ok=True)
        with open(gt.file, "w", encoding="utf-8") as fh:
            fh.write("# Generated by ProofChange — Bob-assisted workflow\n")
            fh.write("# This file is safe to delete; it is regenerated on each run.\n\n")
            fh.write(gt.code)
            fh.write("\n")
        written.append(gt.file)
    return written